project:
  type: website
  output-dir: "C:/Users/ggdoiron.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio"

website:
  title: "Geneviève Doiron"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Photography
      - href: writing.qmd
        text: Writing
      - href: content.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
